### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by raul1991** [raul1991/diver.js#20]
Add tests that would ensure some of the following scenarios

1. Deep level doms should output the corresponding json.
2. Invalid scenarios like 
   1. Invalid Id element passed to the traverse function.
   2. Unsupported elements should be ignored.

Add some more..

**Comment by dangilkerson** [comment]
I can help with this. Which test framework would be preferred?

**Comment by raul1991** [comment]
Hi,

Thanks for taking the time out to work on this. I have been planning to learn about karma for sometime now. If possible do write in that and maybe I can learn from your code as well.
If not that, write in any other framework that you like.

**Comment by dangilkerson** [comment]
Karma it is! :)

**Comment by raul1991** [comment]
Good work on this pull request. Thanks for your support.
